-- ============================================================
-- CodeVault: Oracle Database Schema (Oracle 23c Free)
-- ============================================================

-- USERS: store application users
CREATE TABLE users (
    user_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR2(100) UNIQUE NOT NULL,
    email        VARCHAR2(150) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    avatar_url   VARCHAR2(500),
    bio          VARCHAR2(500),
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- REPOSITORIES: each repo has an owner (user)
CREATE TABLE repositories (
    repo_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_name   VARCHAR2(200) NOT NULL,
    description VARCHAR2(500),
    owner_id    NUMBER NOT NULL,
    visibility  VARCHAR2(20) DEFAULT 'public',
    default_branch VARCHAR2(100) DEFAULT 'main',
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (owner_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- BRANCHES: branches belong to a repo, point to a head commit
CREATE TABLE branches (
    branch_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id       NUMBER NOT NULL,
    branch_name   VARCHAR2(100) NOT NULL,
    head_commit_id NUMBER,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (repo_id) REFERENCES repositories(repo_id) ON DELETE CASCADE
);

-- COMMITS: records commit metadata
CREATE TABLE commits (
    commit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id          NUMBER NOT NULL,
    branch_id        NUMBER NOT NULL,
    author_id        NUMBER NOT NULL,
    message          VARCHAR2(500),
    parent_commit_id NUMBER,
    commit_hash      VARCHAR2(64),
    commit_time      TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (repo_id)   REFERENCES repositories(repo_id) ON DELETE CASCADE,
    FOREIGN KEY (branch_id) REFERENCES branches(branch_id) ON DELETE CASCADE,
    FOREIGN KEY (author_id) REFERENCES users(user_id)
);

-- FILES: versioned file blobs per commit
CREATE TABLE files (
    file_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commit_id    NUMBER NOT NULL,
    file_path    VARCHAR2(500) NOT NULL,
    file_hash    VARCHAR2(200) NOT NULL,
    file_content CLOB,
    file_size    NUMBER DEFAULT 0,
    FOREIGN KEY (commit_id) REFERENCES commits(commit_id) ON DELETE CASCADE
);

-- PULL REQUESTS
CREATE TABLE pull_requests (
    pr_id         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id       NUMBER NOT NULL,
    title         VARCHAR2(300),
    description   VARCHAR2(2000),
    source_branch NUMBER NOT NULL,
    target_branch NUMBER NOT NULL,
    author_id     NUMBER NOT NULL,
    status        VARCHAR2(50) DEFAULT 'open',
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    merged_at     TIMESTAMP,
    FOREIGN KEY (repo_id)       REFERENCES repositories(repo_id) ON DELETE CASCADE,
    FOREIGN KEY (source_branch) REFERENCES branches(branch_id),
    FOREIGN KEY (target_branch) REFERENCES branches(branch_id),
    FOREIGN KEY (author_id)     REFERENCES users(user_id)
);

-- COLLABORATORS: user roles per repository
CREATE TABLE collaborators (
    collab_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id      NUMBER NOT NULL,
    user_id      NUMBER NOT NULL,
    role         VARCHAR2(50) DEFAULT 'viewer',
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (repo_id) REFERENCES repositories(repo_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
);

-- ISSUES
CREATE TABLE issues (
    issue_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    repo_id       NUMBER NOT NULL,
    title         VARCHAR2(300) NOT NULL,
    description   CLOB,
    status        VARCHAR2(50) DEFAULT 'open',
    created_by    NUMBER,
    assignee_id   NUMBER,
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    closed_at     TIMESTAMP,
    FOREIGN KEY (repo_id)    REFERENCES repositories(repo_id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(user_id),
    FOREIGN KEY (assignee_id) REFERENCES users(user_id)
);

-- ISSUE COMMENTS
CREATE TABLE issue_comments (
    comment_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id     NUMBER NOT NULL,
    user_id      NUMBER NOT NULL,
    body         CLOB NOT NULL,
    created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (issue_id) REFERENCES issues(issue_id) ON DELETE CASCADE,
    FOREIGN KEY (user_id)  REFERENCES users(user_id)
);

-- FORKS
CREATE TABLE forks (
    fork_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    original_repo  NUMBER NOT NULL,
    forked_repo    NUMBER NOT NULL,
    forked_by      NUMBER NOT NULL,
    created_at     TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (original_repo) REFERENCES repositories(repo_id),
    FOREIGN KEY (forked_repo)   REFERENCES repositories(repo_id) ON DELETE CASCADE,
    FOREIGN KEY (forked_by)     REFERENCES users(user_id)
);

-- ACTIVITY LOGS (for audit)
CREATE TABLE activity_logs (
    log_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER,
    repo_id     NUMBER,
    action      VARCHAR2(50) NOT NULL,
    details     VARCHAR2(500),
    action_time TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (repo_id) REFERENCES repositories(repo_id) ON DELETE CASCADE
);

-- STARS (bonus)
CREATE TABLE stars (
    star_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL,
    repo_id     NUMBER NOT NULL,
    created_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (repo_id) REFERENCES repositories(repo_id) ON DELETE CASCADE,
    CONSTRAINT uk_stars UNIQUE (user_id, repo_id)
);

-- ============================================================
-- TRIGGERS
-- ============================================================

-- Auto-create "main" branch on new repository
CREATE OR REPLACE TRIGGER trg_default_branch
AFTER INSERT ON repositories
FOR EACH ROW
BEGIN
  INSERT INTO branches(repo_id, branch_name, head_commit_id)
  VALUES(:NEW.repo_id, 'main', NULL);
END;
/

-- Log commit actions
CREATE OR REPLACE TRIGGER trg_log_commit
AFTER INSERT ON commits
FOR EACH ROW
BEGIN
  INSERT INTO activity_logs(user_id, repo_id, action, details)
  VALUES(:NEW.author_id, :NEW.repo_id, 'commit', 'Created commit #' || :NEW.commit_id || ': ' || SUBSTR(:NEW.message, 1, 100));
END;
/

-- Log PR creation
CREATE OR REPLACE TRIGGER trg_log_pr
AFTER INSERT ON pull_requests
FOR EACH ROW
BEGIN
  INSERT INTO activity_logs(user_id, repo_id, action, details)
  VALUES(:NEW.author_id, :NEW.repo_id, 'pull_request', 'Created PR #' || :NEW.pr_id || ': ' || SUBSTR(:NEW.title, 1, 100));
END;
/

-- ============================================================
-- STORED PROCEDURES
-- ============================================================

-- Create a new repository
CREATE OR REPLACE PROCEDURE create_repository(
  p_owner_id    NUMBER,
  p_name        VARCHAR2,
  p_description VARCHAR2,
  p_visibility  VARCHAR2,
  p_repo_id     OUT NUMBER
) AS
BEGIN
  INSERT INTO repositories(owner_id, repo_name, description, visibility)
  VALUES(p_owner_id, p_name, p_description, p_visibility)
  RETURNING repo_id INTO p_repo_id;
END;
/

-- Create a commit record
CREATE OR REPLACE PROCEDURE create_commit(
  p_repo_id        NUMBER,
  p_branch_id      NUMBER,
  p_author_id      NUMBER,
  p_message        VARCHAR2,
  p_parent_commit  NUMBER,
  p_commit_hash    VARCHAR2,
  p_new_commit_id  OUT NUMBER
) AS
BEGIN
  INSERT INTO commits(repo_id, branch_id, author_id, message, parent_commit_id, commit_hash)
  VALUES(p_repo_id, p_branch_id, p_author_id, p_message, p_parent_commit, p_commit_hash)
  RETURNING commit_id INTO p_new_commit_id;

  -- Update branch head
  UPDATE branches SET head_commit_id = p_new_commit_id
  WHERE branch_id = p_branch_id;
END;
/

-- Store file version in a commit
CREATE OR REPLACE PROCEDURE store_file_version(
  p_commit_id  NUMBER,
  p_file_path  VARCHAR2,
  p_file_hash  VARCHAR2,
  p_content    CLOB,
  p_file_size  NUMBER
) AS
BEGIN
  INSERT INTO files(commit_id, file_path, file_hash, file_content, file_size)
  VALUES(p_commit_id, p_file_path, p_file_hash, p_content, p_file_size);
END;
/

-- Create a branch
CREATE OR REPLACE PROCEDURE create_branch(
  p_repo_id      NUMBER,
  p_branch_name  VARCHAR2,
  p_source_commit NUMBER,
  p_branch_id    OUT NUMBER
) AS
BEGIN
  INSERT INTO branches(repo_id, branch_name, head_commit_id)
  VALUES(p_repo_id, p_branch_name, p_source_commit)
  RETURNING branch_id INTO p_branch_id;
END;
/

-- Merge: fast-forward (update target head to source head)
CREATE OR REPLACE PROCEDURE merge_fast_forward(
  p_target_branch_id NUMBER,
  p_source_head_id   NUMBER
) AS
BEGIN
  UPDATE branches
  SET head_commit_id = p_source_head_id
  WHERE branch_id = p_target_branch_id;
END;
/
